defaults: &DEFAULTS
  root_uri: "<%= ENV['ROOT_URI'] %>"
  authenticator:
    name: "database"
  mailer:
    from: "<%= ENV['MAILER_FROM'] %>"
  postmark:
    api:
      uri: "http://api.postmarkapp.com/email"
  smsgateway:
    api:
      uri: "http://smsgateway.me/api/v3/messages/send"

development:
  <<: *DEFAULTS

test:
  <<: *DEFAULTS

production:
  <<: *DEFAULTS