defaults: &DEFAULTS
  root_uri: "<%= ENV['ROOT_URI'] %>"
  authenticator:
    name: "database"
  mailer:
    from: "<%= ENV['MAILER_FROM'] %>"
  notifier:
    api:
      uri: "<%= ENV['NOTIFIER_API_URI'] %>"

development:
  <<: *DEFAULTS

test:
  <<: *DEFAULTS

production:
  <<: *DEFAULTS